typeset -U path PATH

setopt HIST_IGNORE_ALL_DUPS

WORDCHARS=${WORDCHARS//[\/]}

ZSH_AUTOSUGGEST_MANUAL_REBIND=1

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

function zvm_config() {
  ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BEAM
  ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK
}

ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  if (( ${+commands[curl]} )); then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  else
    mkdir -p ${ZIM_HOME} && wget -nv -O ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  fi
fi

if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh

alias cdg='cd "$(git root)"'

zmodload -F zsh/terminfo +p:terminfo

zvm_after_init_commands+=('
  for key ("^[[A" "^P" ${terminfo[kcuu1]}) bindkey ${key} history-substring-search-up
  for key ("^[[B" "^N" ${terminfo[kcud1]}) bindkey ${key} history-substring-search-down
  unset key
')

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PYENV_ROOT/shims:$PATH"
pyenv() { unset -f pyenv; eval "$(command pyenv init - zsh)"; pyenv "$@"; }

eval "$(direnv hook zsh)"

export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.flare.zsh ] && source ~/.flare.zsh
[ -f ~/.git-worktree.zsh ] && source ~/.git-worktree.zsh
export PATH="$HOME/.local/bin:$PATH"
